'use strict';

module.exports = {
	ADDING_NO_SUCH_PARENT: {},
	ADDING_DUPLICATED: {},
	ADDING_INVALID_PARENT_TYPE: {},
	ADDING_INVALID_ATTRIBUTES: {},
	ADDING_STORE_FAILED: {},

	SEARCHING_INVALID_XPATH: {},

	DELETING_NO_SUCH_ELEMENT: {},
	DELETING_STORE_FAILED: {},

	MODIFYING_NO_SUCH_ELEMENT: {},
	MODIFYING_INVALID_ATTRIBUTES: {},
	MODIFYING_STORE_FAILED: {},

	MOVING_CIRCULAR_REFERENCE: {},
	MOVING_NO_SUCH_PARENT: {},
	MOVING_NO_SUCH_ELEMENT: {},
	MOVING_STORE_FAILED: {}
};
